# Generation Configurations
generation:
  niter: 2500
  stages: 24
  concurrent: 20
  act_func: prelu
  n_samples_generate: 3
  im_min_size: 120
  im_max_size: 614

# Segmentation Configurations
segmentation:
  niter: 1000
  l_rate: 0.01
  b_size: 3
  scheduler: "step"

# Harmonisation Configurations
harmonisation:
  niter: 1000
  stages: 16
  act_func: prelu
  concurrent: 9
  im_min_size: 120
  im_max_size: 614
  lrelu_alpha: 0.3
